---
# tasks file for sql-server 
# This creates directory structure

# create SQL Directories
- name: create directory structure
  win_file:
    path: C:\scripts
    state: directory
  when: ansible_os_family == "Windows"

# Copying Scripts To Server
###########################


- name: script to server add_gmsa_accounts.ps1"
  win_copy:
    src: "/etc/ansible/files/scripts/add-gmsa-accounts.ps1"
    dest: C:\scripts\add-gmsa-accounts.ps1
  when: ansible_os_family == "Windows"
