---
# tasks file for web-server role
# this will complete configure and install all software required for the sql server role
- name: Update group_vars for ansible winrm connection to kerberos
  lineinfile:
    path: /etc/ansible/group_vars/all.yml
    regexp: 'ansible_winrm_transport: '
    line: "ansible_winrm_transport: credssp"
  delegate_to: 127.0.0.1

# Load Variable File that was updated
- name: Include /etc/ansible/group_vars/all.yml
  include_vars: /etc/ansible/group_vars/all.yml

#- name: provisions disk
#  include_tasks: provision_disk.yml

#- name: installs software via package manager
#  include_tasks: software_setup.yml

#- name: ensure that a reboot is not pending
#  when: ansible_reboot_pending
#  debug:
#    msg: 'pending reboot detected'
# changed_when: true
#  notify: reboot windows

#- meta: flush_handlers

#- name: copy Scripts to local host
#  include_tasks: copy_scripts.yml

- name: create required directories
  include_tasks: create_directories.yml

#- name: installs required powershell modules
#  include_tasks: powershell_modules.yml

#- name: installs required windows features
#  include_tasks: windows_features.yml

#- name: ensure that a reboot is not pending
#  when: ansible_reboot_pending
#  debug:
#    msg: 'pending reboot detected'
#  changed_when: true
#  notify: reboot windows

#- name: run powershell task for sql server setup
#  include_tasks: powershell_task.yml

#- name: setup local admins
#  include_tasks: setup_local_admins.yml

- name: setup iis
  include_tasks: iis_setup.yml


- name: Update group_vars for ansible winrm connection to kerberos
  lineinfile:
    path: /etc/ansible/group_vars/all.yml
    regexp: 'ansible_winrm_transport: '
    line: "ansible_winrm_transport: credssp"
  delegate_to: 127.0.0.1


