---
# tasks file for print-server
- name: Include Windows Server User Groups Variables
  include_vars: serversetup.yml

- name: Install Print Server Services
  ansible.windows.win_feature:
    name: Print-Server
    state: present
    include_management_tools: yes
  register: win_feature

- name: Reboot if installing Print-Server feature requires it
  ansible.windows.win_reboot:
  when: win_feature.reboot_required

- include: /etc/ansible/playbooks/add-local-admin.yml
  vars:
    localusergroup: Administrators
    usergroups: "{{admingroups}}"
