---
# tasks file for windows-server
#Standard Configurations for Windows Server Setup

- include_vars: "{{ansible_facts.system_info.local_facts.server_environment + '-' + ansible_facts.system_info.local_facts.server_owner + '-admins.yml'}}"

## adding the group managed service accounts based on environment 

- name: add standarnd sql admins
  win_group_membership:
    name: Administrators
    members:
      - "{{item}}"
    state: present
  loop: "{{ sql_admin_groups }}"

- name: "{{ ansible_facts.system_info.local_facts.server_environment}} - {{ansible_facts.system_info.local_facts.server_owner}} -  add standard local admins"
  win_group_membership:
    name: Administrators
    members:
      - "{{item}}"
    state: present
  loop: "{{ admin_groups }}"

