---
# vars file for sql-role
# environment: qa
# team: integrations
# standard admin groups
#Specifies what user(s) and group(S) will be added to the local admin group

admin_groups:
  - CORP\Integrations_QA_Server_Admins
  - CORP\SQLAdminProd
